using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Test.Business.Abstract;
using Test.Entities.Concrete;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Test.WebApi.Controllers
{
	/// <summary>
	/// Generated by ElementalBuilder (12.11.2019 16:39:22)
	/// </summary>
	[Route("api/[controller]")]
	[ApiController]
	public class EmlakController : ControllerBase 
	{
		 private IEmlakService _emlakService; 
		 public EmlakController(IEmlakService emlakService) 
		{
			_emlakService = emlakService;
		}

		[HttpGet]
		public IActionResult Get() 
		{
			try
			{
				var Emlak= _emlakService.GetAllEmlak();
				if (Emlak == null) 
					return NotFound("There are no Emlak in db!"); 
				return Ok(Emlak);

			}
			catch
			{
				return BadRequest();

			}

		}


		[HttpGet("{id}")]
		public IActionResult Get(int id) 
		{
			try
			{
				var emlak = _emlakService.GetEmlakById(id);
				if (emlak == null) 
					return NotFound("There is no emlak with id:" + id); 
				return Ok(emlak);

			}
			catch
			{
				return BadRequest();

			}

		}


		[HttpPost]
		public IActionResult Post([FromBody]Emlak emlak) 
		{
			try
			{
				var result = _emlakService.Add(emlak);
				if (result == 0) 
					return BadRequest("Error: Data not saved!");

				return new StatusCodeResult(201);

			}
			catch(Exception exception)
			{
				return BadRequest("Error: Data not saved! Error:"+ exception.Message);

			}

		}


		[HttpPut]
		public IActionResult Put([FromBody]Emlak emlak) 
		{
			try
			{
				var result= _emlakService.Update(emlak);
				if(result == 0) 
					return BadRequest("Error: Data not updated!");

				return new StatusCodeResult(201);

			}
			catch(Exception exception)
			{
				return BadRequest("Error: Data not updated! Error:"+ exception.Message);

			}

		}


		[HttpDelete("{id}")] 
		public IActionResult Delete(int id) 
		{
			try
			{
				var result= _emlakService.Delete(id);
				if(result == 0) 
					return BadRequest("Error: Data not deleted!");

				return new StatusCodeResult(201);

			}
			catch(Exception exception)
			{
				return BadRequest("Error: Data not deleted! Error:"+ exception.Message);

			}

		}


	}
}
	// C:\Users\manas\source\repos\Test\Test.WebApi\Controllers 
