using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Test.Business.Abstract;
using Test.Entities.Concrete;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Test.WebApi.Controllers
{
	/// <summary>
	/// Generated by ElementalBuilder (12.11.2019 16:39:22)
	/// </summary>
	[Route("api/[controller]")]
	[ApiController]
	public class IsyeriController : ControllerBase 
	{
		 private IIsyeriService _ısyeriService; 
		 public IsyeriController(IIsyeriService ısyeriService) 
		{
			_ısyeriService = ısyeriService;
		}

		[HttpGet]
		public IActionResult Get() 
		{
			try
			{
				var Isyeri= _ısyeriService.GetAllIsyeri();
				if (Isyeri == null) 
					return NotFound("There are no Isyeri in db!"); 
				return Ok(Isyeri);

			}
			catch
			{
				return BadRequest();

			}

		}


		[HttpGet("{id}")]
		public IActionResult Get(int id) 
		{
			try
			{
				var ısyeri = _ısyeriService.GetIsyeriById(id);
				if (ısyeri == null) 
					return NotFound("There is no ısyeri with id:" + id); 
				return Ok(ısyeri);

			}
			catch
			{
				return BadRequest();

			}

		}


		[HttpPost]
		public IActionResult Post([FromBody]Isyeri ısyeri) 
		{
			try
			{
				var result = _ısyeriService.Add(ısyeri);
				if (result == 0) 
					return BadRequest("Error: Data not saved!");

				return new StatusCodeResult(201);

			}
			catch(Exception exception)
			{
				return BadRequest("Error: Data not saved! Error:"+ exception.Message);

			}

		}


		[HttpPut]
		public IActionResult Put([FromBody]Isyeri ısyeri) 
		{
			try
			{
				var result= _ısyeriService.Update(ısyeri);
				if(result == 0) 
					return BadRequest("Error: Data not updated!");

				return new StatusCodeResult(201);

			}
			catch(Exception exception)
			{
				return BadRequest("Error: Data not updated! Error:"+ exception.Message);

			}

		}


		[HttpDelete("{id}")] 
		public IActionResult Delete(int id) 
		{
			try
			{
				var result= _ısyeriService.Delete(id);
				if(result == 0) 
					return BadRequest("Error: Data not deleted!");

				return new StatusCodeResult(201);

			}
			catch(Exception exception)
			{
				return BadRequest("Error: Data not deleted! Error:"+ exception.Message);

			}

		}


	}
}
	// C:\Users\manas\source\repos\Test\Test.WebApi\Controllers 
