using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Test.Business.Abstract;
using Test.Entities.Concrete;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Test.WebApi.Controllers
{
	/// <summary>
	/// Generated by ElementalBuilder (12.11.2019 16:39:22)
	/// </summary>
	[Route("api/[controller]")]
	[ApiController]
	public class MusteriController : ControllerBase 
	{
		 private IMusteriService _musteriService; 
		 public MusteriController(IMusteriService musteriService) 
		{
			_musteriService = musteriService;
		}

		[HttpGet]
		public IActionResult Get() 
		{
			try
			{
				var Musteri= _musteriService.GetAllMusteri();
				if (Musteri == null) 
					return NotFound("There are no Musteri in db!"); 
				return Ok(Musteri);

			}
			catch
			{
				return BadRequest();

			}

		}


		[HttpGet("{id}")]
		public IActionResult Get(int id) 
		{
			try
			{
				var musteri = _musteriService.GetMusteriById(id);
				if (musteri == null) 
					return NotFound("There is no musteri with id:" + id); 
				return Ok(musteri);

			}
			catch
			{
				return BadRequest();

			}

		}


		[HttpPost]
		public IActionResult Post([FromBody]Musteri musteri) 
		{
			try
			{
				var result = _musteriService.Add(musteri);
				if (result == 0) 
					return BadRequest("Error: Data not saved!");

				return new StatusCodeResult(201);

			}
			catch(Exception exception)
			{
				return BadRequest("Error: Data not saved! Error:"+ exception.Message);

			}

		}


		[HttpPut]
		public IActionResult Put([FromBody]Musteri musteri) 
		{
			try
			{
				var result= _musteriService.Update(musteri);
				if(result == 0) 
					return BadRequest("Error: Data not updated!");

				return new StatusCodeResult(201);

			}
			catch(Exception exception)
			{
				return BadRequest("Error: Data not updated! Error:"+ exception.Message);

			}

		}


		[HttpDelete("{id}")] 
		public IActionResult Delete(int id) 
		{
			try
			{
				var result= _musteriService.Delete(id);
				if(result == 0) 
					return BadRequest("Error: Data not deleted!");

				return new StatusCodeResult(201);

			}
			catch(Exception exception)
			{
				return BadRequest("Error: Data not deleted! Error:"+ exception.Message);

			}

		}


	}
}
	// C:\Users\manas\source\repos\Test\Test.WebApi\Controllers 
