using System;
using System.Collections.Generic;
using System.Text;

namespace Test.Core.Entities
{
	/// <summary>
	/// Generated by ElementalBuilder (12.11.2019 16:39:22)
	/// </summary>
	public interface IEntity
	{
	}
}
	// C:\Users\manas\source\repos\Test\Test.Core\Entities 
