using System;
using System.Collections.Generic;
using System.Text;
using System.Linq.Expressions;
using Test.Business.Abstract;
using Test.DataAccess.Abstract;
using Test.Entities.Concrete;

namespace Test.Business.Concrete
{
	/// <summary>
	/// Generated by ElementalBuilder (12.11.2019 16:39:22)
	/// </summary>
	public class EmlakManager : IEmlakService 
	{
		 private IEmlakDal _emlakDal; 
		 public EmlakManager(IEmlakDal emlakDal) 
		{
			_emlakDal = emlakDal;
		}

		public List<Emlak> GetAllEmlak() 
		{
			return _emlakDal.GetList();
		}

		public Emlak GetEmlakById(int Id) 
		{
			return _emlakDal.Get(x=>x.EmlakId_PK == Id); 
		}

		public int Add(Emlak entity) 
		{
			return _emlakDal.Add(entity); 
		}

		public int Update(Emlak entity) 
		{
			return _emlakDal.Update(entity); 
		}

		public int Delete(int Id) 
		{
			return _emlakDal.Delete(new Emlak{EmlakId_PK = Id}); 
		}

	}
}
	// C:\Users\manas\source\repos\Test\Test.Business\Concrete 
