using System;
using System.Collections.Generic;
using System.Text;
using System.Linq.Expressions;
using Test.Business.Abstract;
using Test.DataAccess.Abstract;
using Test.Entities.Concrete;

namespace Test.Business.Concrete
{
	/// <summary>
	/// Generated by ElementalBuilder (12.11.2019 16:39:22)
	/// </summary>
	public class IsyeriManager : IIsyeriService 
	{
		 private IIsyeriDal _ısyeriDal; 
		 public IsyeriManager(IIsyeriDal ısyeriDal) 
		{
			_ısyeriDal = ısyeriDal;
		}

		public List<Isyeri> GetAllIsyeri() 
		{
			return _ısyeriDal.GetList();
		}

		public Isyeri GetIsyeriById(int Id) 
		{
			return _ısyeriDal.Get(x=>x.IsYeriId_PK == Id); 
		}

		public int Add(Isyeri entity) 
		{
			return _ısyeriDal.Add(entity); 
		}

		public int Update(Isyeri entity) 
		{
			return _ısyeriDal.Update(entity); 
		}

		public int Delete(int Id) 
		{
			return _ısyeriDal.Delete(new Isyeri{IsYeriId_PK = Id}); 
		}

	}
}
	// C:\Users\manas\source\repos\Test\Test.Business\Concrete 
