// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test.DataAccess.Concrete.EntityFramework;

namespace Test.DataAccess.Migrations
{
    [DbContext(typeof(TestDbContext))]
    partial class TestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Test.Entities.Concrete.Emlak", b =>
                {
                    b.Property<int>("EmlakId_PK")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BinaKati");

                    b.Property<string>("EmlakTur");

                    b.Property<string>("IsinmaTur");

                    b.Property<int>("Kat");

                    b.Property<int>("Metrekare");

                    b.Property<int>("OdaSayisi");

                    b.HasKey("EmlakId_PK");

                    b.ToTable("Emlak");
                });

            modelBuilder.Entity("Test.Entities.Concrete.Isyeri", b =>
                {
                    b.Property<int>("IsYeriId_PK")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adres");

                    b.Property<string>("Fax");

                    b.Property<string>("Telefon");

                    b.Property<string>("Yetkili");

                    b.Property<string>("isletmeAdi");

                    b.HasKey("IsYeriId_PK");

                    b.ToTable("Isyeri");
                });

            modelBuilder.Entity("Test.Entities.Concrete.Musteri", b =>
                {
                    b.Property<int>("MusteriId_PK")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adi");

                    b.Property<string>("Adres");

                    b.Property<string>("CepTel");

                    b.Property<string>("Email");

                    b.Property<string>("EvTel");

                    b.Property<string>("Soyadi");

                    b.HasKey("MusteriId_PK");

                    b.ToTable("Musteri");
                });

            modelBuilder.Entity("Test.Entities.Concrete.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EMail");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
