using System;
using System.Collections.Generic;
using System.Text;
using System.Linq.Expressions;
using Test.Entities.Concrete;

namespace Test.Business.Abstract
{
	/// <summary>
	/// Generated by ElementalBuilder (12.11.2019 16:39:22)
	/// </summary>
	public interface IEmlakService 
	{
		 List<Emlak> GetAllEmlak(); 
		 Emlak GetEmlakById(int EmlakId); 
		 int Add(Emlak emlak); 
		 int Update(Emlak emlak); 
		 int Delete(int emlakId); 
	}
}
	// C:\Users\manas\source\repos\Test\Test.Business\Abstract 
