using System;
using System.Collections.Generic;
using System.Text;
using System.Linq.Expressions;
using Test.Entities.Concrete;

namespace Test.Business.Abstract
{
	/// <summary>
	/// Generated by ElementalBuilder (12.11.2019 16:39:22)
	/// </summary>
	public interface IIsyeriService 
	{
		 List<Isyeri> GetAllIsyeri(); 
		 Isyeri GetIsyeriById(int IsyeriId); 
		 int Add(Isyeri ısyeri); 
		 int Update(Isyeri ısyeri); 
		 int Delete(int ısyeriId); 
	}
}
	// C:\Users\manas\source\repos\Test\Test.Business\Abstract 
