using System;
using System.Collections.Generic;
using System.Text;
using System.Linq.Expressions;
using Test.Entities.Concrete;

namespace Test.Business.Abstract
{
	/// <summary>
	/// Generated by ElementalBuilder (12.11.2019 16:39:22)
	/// </summary>
	public interface IMusteriService 
	{
		 List<Musteri> GetAllMusteri(); 
		 Musteri GetMusteriById(int MusteriId); 
		 int Add(Musteri musteri); 
		 int Update(Musteri musteri); 
		 int Delete(int musteriId); 
	}
}
	// C:\Users\manas\source\repos\Test\Test.Business\Abstract 
