using System;
using System.Collections.Generic;
using System.Text;
using Test.Entities.Concrete;

namespace Test.Business.Abstract
{
	/// <summary>
	/// Generated by ElementalBuilder (12.11.2019 16:39:22)
	/// </summary>
	public interface IUserService 
	{
		 int Register(User user, string password); 
		 User Login(string eMail, string password); 
		 bool UserExists(string eMail); 
	}
}
	// C:\Users\manas\source\repos\Test\Test.Business\Abstract 
