using Test.DataAccess.Abstract;
using Test.Entities.Concrete;
using Test.Core.DataAccess.EntityFramework;
using System;
using System.Collections.Generic;
using System.Text;

namespace Test.DataAccess.Concrete.EntityFramework
{
	/// <summary>
	/// Generated by ElementalBuilder (12.11.2019 16:39:22)
	/// </summary>
	public class EfMusteriDal:EfRepositoryBase<Musteri,TestDbContext>,IMusteriDal
	{
	// Special operations write here! 
	}
}
	// C:\Users\manas\source\repos\Test\Test.DataAccess\Concrete\EntityFramework 
