using System;
using System.Collections.Generic;
using System.Text;
using Test.Core.DataAccess.EntityFramework;
using Test.DataAccess.Abstract;
using Test.Entities.Concrete;

namespace Test.DataAccess.Concrete.EntityFramework
{
	/// <summary>
	/// Generated by ElementalBuilder (12.11.2019 16:39:22)
	/// </summary>
	public class EfUserDal:EfRepositoryBase<User,TestDbContext >,IUserDal 
	{
	}
}
	// C:\Users\manas\source\repos\Test\Test.DataAccess\Concrete\EntityFramework 
