using System;
using System.Collections.Generic;
using System.Text;

namespace Test.DataAccess 
{
	/// <summary>
	/// Generated by ElementalBuilder (12.11.2019 16:39:22)
	/// </summary>
	 public static class _GlobalFields
	{
		public static string ConnectionStr = "server = BERKAYSRN\\SQLEXPRESS ; Database = emlakDb; User Id=sa; Password=P5gplmnxms1.;"; 
	}
}
	// C:\Users\manas\source\repos\Test\Test.DataAccess\ 
