using System;
using System.Collections.Generic;
using System.Text;
using Test.Core.DataAccess;
using Test.Entities.Concrete;

namespace Test.DataAccess.Abstract
{
	/// <summary>
	/// Generated by ElementalBuilder (12.11.2019 16:39:22)
	/// </summary>
	public interface IUserDal:IRepository<User> 
	{
	}
}
	// C:\Users\manas\source\repos\Test\Test.DataAccess\Abstract 
