using System;
using System.Collections.Generic;
using System.Text;
using System.Linq.Expressions;
using Test.Core.Entities;

namespace Test.Core.DataAccess
{
	/// <summary>
	/// Generated by ElementalBuilder (12.11.2019 16:39:22)
	/// </summary>
	public interface IRepository<TEntity> where TEntity:class , IEntity,new() 
	{
		 List<TEntity> GetList(Expression<Func<TEntity,bool>> filter = null); 
		 TEntity Get(Expression<Func<TEntity, bool>> filter); 
		 int Add(TEntity entity); 
		 int Update(TEntity entity); 
		 int Delete(TEntity entity); 
	}
}
	// C:\Users\manas\source\repos\Test\Test.Core\DataAccess 
