using Test.Core.Entities;
using System;
using System.Collections.Generic;
using System.Text;
using System.ComponentModel.DataAnnotations;

namespace Test.Entities.Concrete
{
	/// <summary>
	/// Generated by ElementalBuilder (12.11.2019 16:39:22)
	/// </summary>
	public class Isyeri:IEntity
	{
        #region Properties 
        [Key]

        public Int32 IsYeriId_PK { get; set; }
		public String isletmeAdi { get; set; }
		public String Yetkili { get; set; }
		public String Adres { get; set; }
		public String Telefon { get; set; }
		public String Fax { get; set; }
		#endregion 

	}
}
	// C:\Users\manas\source\repos\Test\Test.Entities\Concrete 
