using Test.Core.Entities;
using System;
using System.Collections.Generic;
using System.Text;
using System.ComponentModel.DataAnnotations;

namespace Test.Entities.Concrete
{
	/// <summary>
	/// Generated by ElementalBuilder (12.11.2019 16:39:22)
	/// </summary>
	public class Musteri:IEntity
	{
        #region Properties 
        [Key]

        public Int32 MusteriId_PK { get; set; }
		public String Adi { get; set; }
		public String Soyadi { get; set; }
		public String EvTel { get; set; }
		public String CepTel { get; set; }
		public String Email { get; set; }
		public String Adres { get; set; }
		#endregion 

	}
}
	// C:\Users\manas\source\repos\Test\Test.Entities\Concrete 
