using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text;
using Test.Core.Entities;

namespace Test.Entities.Concrete
{
	/// <summary>
	/// Generated by ElementalBuilder (12.11.2019 16:39:22)
	/// </summary>
	public class User:IEntity 
	{
        [Key]
        public int Id { get; set; } 
		public string FirstName { get; set; } 
		public string LastName { get; set; } 
		public string EMail { get; set; } 
		public byte[] PasswordHash { get; set; } 
		public byte[] PasswordSalt { get; set; } 
	}
}
	// C:\Users\manas\source\repos\Test\Test.Entities\Concrete 
