using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;

namespace Test.WebApi.CustomMiddleware
{
	/// <summary>
	/// Generated by ElementalBuilder (12.11.2019 16:39:22)
	/// </summary>
	public class BasicAuthenticationMiddleware 
	{
		private readonly RequestDelegate _next; 
		public BasicAuthenticationMiddleware(RequestDelegate next) 
		{
			_next = next;
		}

		public async Task Invoke(HttpContext context) 
		{
			string autHeader = context.Request.Headers["Authorization"]; 
			if (autHeader != null && autHeader.StartsWith("basic",StringComparison.OrdinalIgnoreCase))
			{
				string token = autHeader.Substring(6).Trim();
				string credentialString = Encoding.UTF8.GetString(Convert.FromBase64String(token));
				string[] credentials = credentialString.Split(':');
				if (credentials[0] == "serkan" && credentials[1] == "123")
				{
					await _next(context);
				}
				else
				{
					context.Response.StatusCode = 401;//Unauthorized
				}
			}
			else
			{
			context.Response.StatusCode = 401;//Unauthorized
			}
		}

	}
}
	// C:\Users\manas\source\repos\Test\Test.WebApi\CustomMiddleware 
