using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;

namespace Test.WebApi.Helpers
{
	/// <summary>
	/// Generated by ElementalBuilder (12.11.2019 16:39:22)
	/// </summary>
	public static class JwtExtension 
	{
		public static void AddApplicationError(this HttpResponse response, string message) 
		{
			response.Headers.Add("Application - Error",message); 
			response.Headers.Add("Access - Control - Allow - Origin"," * "); 
			response.Headers.Add("Access - Control - Expose - Header","Application - Error"); 
		}
	}
}
	// C:\Users\manas\source\repos\Test\Test.WebApi\Helpers 
