using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Test.WebApi.Dtos
{
	/// <summary>
	/// Generated by ElementalBuilder (12.11.2019 16:39:22)
	/// </summary>
	public class UserDto 
	{
		public string FirstName { get; set; } 
		public string LastName { get; set; } 
		public string EMail { get; set; } 
		public string Password { get; set; } 
	}
}
	// C:\Users\manas\source\repos\Test\Test.WebApi\Dtos 
